### PR TITLE
Make dynamic property assignment in `DataRecord` safer

### PR DESCRIPTION
**Pull request by ramipellumbi**
- Fix all lint errors in `elements/`
- Add `| None` typing to class values that initialize to `None` in `logical.py`
- Explicit pass of `None` in for `input_schema` on `CacheScan`

### CODE REVIEW

**Comment by mdr223** [comment]
Pushed a small commit to:
- Apply a sanity check (to replace our previous setting of `kwargs['inputSchema'] = None`) to formally ensure that we never initialize `CacheScan` or `BaseScan` with a value other than `None`
- Give `inputSchema` a default setting of `None` in `LogicalOperator`. Without this, the call to the `BaseScan` constructor in the `Optimizer` would throw an exception. I considered just adding `inputSchema=None` to that constructor call, but I want to enforce correct behavior where possible.
- Heeded the advice of Ruff to remove `[]` as a default value in function signatures
- Made `schema` a property of the `Set` class; this has been a long-needed fix (kudos to @ramipellumbi for planting the `property` seed elsewhere) and is also needed for L142 in `optimizer.py`
- Fixed a fun bug 🐛 where the definition of `__setattr__` and `__getattr__` in `DataRecord` created an infinite recursion loop b/c when we initialized `self._data = {}` in the constructor, it would call `__setattr__(self, "_data", {})`. This would in turn call `__getattr__(self, "_data")` (from the `else` branch of `__setattr__`) which would then call itself (`__getattr__`) infinitely many times on the line `if name in self._data:`
- Removed `scan_idx` from list of class attributes in `__setattr__` b/c we really want it to be discarded after the constructor

**Comment by ramipellumbi** [comment]
> Pushed a small commit to:
> 
>     * Apply a sanity check (to replace our previous setting of `kwargs['inputSchema'] = None`) to formally ensure that we never initialize `CacheScan` or `BaseScan` with a value other than `None`
> 
>     * Give `inputSchema` a default setting of `None` in `LogicalOperator`. Without this, the call to the `BaseScan` constructor in the `Optimizer` would throw an exception. I considered just adding `inputSchema=None` to that constructor call, but I want to enforce correct behavior where possible.
> 
>     * Heeded the advice of Ruff to remove `[]` as a default value in function signatures
> 
>     * Made `schema` a property of the `Set` class; this has been a long-needed fix (kudos to @ramipellumbi for planting the `property` seed elsewhere) and is also needed for L142 in `optimizer.py`
> 
>     * Fixed a fun bug 🐛 where the definition of `__setattr__` and `__getattr__` in `DataRecord` created an infinite recursion loop b/c when we initialized `self._data = {}` in the constructor, it would call `__setattr__(self, "_data", {})`. This would in turn call `__getattr__(self, "_data")` (from the `else` branch of `__setattr__`) which would then call itself (`__getattr__`) infinitely many times on the line `if name in self._data:`
> 
>     * Removed `scan_idx` from list of class attributes in `__setattr__` b/c we really want it to be discarded after the constructor

Dang, the recursion bug is a goofy mistake -- my bad

**Comment by ramipellumbi** [comment]
> Pushed a small commit to:
> 
>     * Apply a sanity check (to replace our previous setting of `kwargs['inputSchema'] = None`) to formally ensure that we never initialize `CacheScan` or `BaseScan` with a value other than `None`
> 
>     * Give `inputSchema` a default setting of `None` in `LogicalOperator`. Without this, the call to the `BaseScan` constructor in the `Optimizer` would throw an exception. I considered just adding `inputSchema=None` to that constructor call, but I want to enforce correct behavior where possible.
> 
>     * Heeded the advice of Ruff to remove `[]` as a default value in function signatures
> 
>     * Made `schema` a property of the `Set` class; this has been a long-needed fix (kudos to @ramipellumbi for planting the `property` seed elsewhere) and is also needed for L142 in `optimizer.py`
> 
>     * Fixed a fun bug 🐛 where the definition of `__setattr__` and `__getattr__` in `DataRecord` created an infinite recursion loop b/c when we initialized `self._data = {}` in the constructor, it would call `__setattr__(self, "_data", {})`. This would in turn call `__getattr__(self, "_data")` (from the `else` branch of `__setattr__`) which would then call itself (`__getattr__`) infinitely many times on the line `if name in self._data:`
> 
>     * Removed `scan_idx` from list of class attributes in `__setattr__` b/c we really want it to be discarded after the constructor

The ruff lint point should be a public PSA. Python default arguments to functions are evaluated WHEN THE FUNCTION IS DEFINED NOT CALLED. So, if you have a mutable default argument like a list or set, that will be shared across all calls. Very bad. E.g.,

```
def append_to(element, to=[]):
    to.append(element)

my_list  = append_to(12) # [12]
my_other_list = append_to(42) # [12, 42]

```

**Review by mdr223 — APPROVED** [review]
Passing tests + demos

**Pull request merged**
